### ISSUE TITLE
Use Releases

### ISSUE THREAD

**Issue by jhartlep** [Admidio/docker#6]
Hi
I just tried your admidio docker image.
Great. Thanks.
But I have on issue.

If I use admidio/admidio:php7_latest I get the beta 4.0.0 Beta 1
For latest I would expect not a beta, but the latest release version - which is 3.3.7
But I can only use admidio/admidio:php7_v3.3.5 (v.3.3.7 does not exist).

Could you change this please for latest (or add a stable tag) for the latest stable?

**Comment by Brawn1** [comment]
Sorry, tomorrow is the New Release online.

**Comment by Brawn1** [comment]
In my opinion latest is the master branch and this is the current development version. The stable branch is the latest v3.3.?

**Comment by Brawn1** [comment]
Docker images is now updated and pushed.
Thank you for your patience.
